### ISSUE TITLE
Install proceeds until the "Confirm and submit" phase

### ISSUE THREAD

**Issue by clstrfck-git** [DSJAS/DSJAS#1]
New to scambaing here!
Not a developer or programmer either.
I am familiar and comfortable with WordPress so your package seemed like a good way to move forward with a bogus bank for making life difficult for scummy scammers.
I've been looking for a "custom" banking solution that would be flexible enough to adapt and appear realistic as possible
Saw your post on BobRTC and decided to try it out on a secure domain.

I have a Northwatch bank setup on another secure domain so I can do some basic web host stuff.

Installed your package on a free hosting server that has Let's Encrypt SSL and a few other limited features.
The install screen appears on my registered domain, verfication works, database connection works but then I get kicked back to "Continue to install-verification" screen again.

![1-Screenshot_2020-09-19_Regenerating-Token](https://user-images.githubusercontent.com/67506651/93685957-4f2f4300-fa70-11ea-91c3-f2c62674d2eb.png)
![2-Screenshot_2020-09-19-_Authentication-Success](https://user-images.githubusercontent.com/67506651/93685958-50f90680-fa70-11ea-99dd-c67823da93a3.png)
![3-Screenshot_2020-09-19_Database-Setup_edit](https://user-images.githubusercontent.com/67506651/93685959-522a3380-fa70-11ea-832f-91cde5b89342.png)
![4-Screenshot_2020-09-19_Database-Success _edit](https://user-images.githubusercontent.com/67506651/93685961-52c2ca00-fa70-11ea-8d62-ce6d4fab5fc4.png)
![5-Screenshot_2020-09-19_Back-to-Install-Verification](https://user-images.githubusercontent.com/67506651/93685963-53f3f700-fa70-11ea-8311-746f1ee8af26.png)

Using Vivaldi and Firefox (with and without extensions)
No difference.

Any advice would be welcome.
This would be the perfect tool to compliment the VM I've built.

Thanks.

**Comment by OverEngineeredCode** [comment]
Hello and thanks for the issue!

I've done some debugging and have determined a likely cause for the issue. To aid in the fixing of this, would you mind telling me if any of your database info contained special characters - especially characters such as "=", "&" or any quotes? If this is the case, I have a patch written up that should fix this issue.

As a temporary workaround, you could try setting your database credentials to just alphanumeric characters. I know this isn't the most secure, but it will just be temporary. Also, any settings you later save (such as bank name or URL) shouldn't contain any special characters for now.

Sorry for any annoyance this probably caused (I know I would be annoyed if this happened to me). Hopefully, I will be able to fix the problem relatively quickly.

**Comment by OverEngineeredCode** [comment]
Ok, I believe I have fixed this. I'll push out an update as soon as possible to get this fixed for everybody else. Thanks a lot for the report, hopefully you manage fine after this.

If you have any more issues, you might need to reset your config to defaults by re-downloading the program. Hopefully, though, that shouldn't be a problem.

**Comment by clstrfck-git** [comment]
> Hello and thanks for the issue!
> 
> I've done some debugging and have determined a likely cause for the issue. To aid in the fixing of this, would you mind telling me if any of your database info contained special characters - especially characters such as "=", "&" or any quotes? If this is the case, I have a patch written up that should fix this issue.
> 
> As a temporary workaround, you could try setting your database credentials to just alphanumeric characters. I know this isn't the most secure, but it will just be temporary. Also, any settings you later save (such as bank name or URL) shouldn't contain any special characters for now.
> 
> In case you are interested, the problem relates to this:
> 
> ![PHP documentation](https://user-images.githubusercontent.com/45273541/93687374-5b89bf00-fab5-11ea-8115-38fce6372c3f.png)
> 
> DSJAS was not doing this, and so the configuration file is being broken by these characters.
> 
> Sorry for any annoyance this probably caused (I know I would be annoyed if this happened to me). Hopefully, I will be able to fix the problem relatively quickly.

This is not an annoyance as it's staight out of the box and unexpecteds isuses arise anytime so no worries.

Thanks for responding.
I'm sunk as far as strickly alphnumeric characters as the free host insists on generating a username ending with an underscore "_". No way around it.

"username"_"XXXXXX"
It's a free service so I'll not complain.


Your program actually is easily reset by deleting the Config.ini, much like deleting the wp-config.php in WP

**Comment by clstrfck-git** [comment]
> Ok, I believe I have fixed this. I'll push out an update as soon as possible to get this fixed for everybody else. Thanks a lot for the report, hopefully you manage fine after this.
> 
> If you have any more issues, you might need to reset your config to defaults by re-downloading the program. Hopefully, though, that shouldn't be a problem.

I'll keep updated.
Thanks.

**Comment by clstrfck-git** [comment]
> Ok, I believe I have fixed this. I'll push out an update as soon as possible to get this fixed for everybody else. Thanks a lot for the report, hopefully you manage fine after this.
> 
> If you have any more issues, you might need to reset your config to defaults by re-downloading the program. Hopefully, though, that shouldn't be a problem.

New install of updated package resulted i getting to the Administrative user setup.
Kudos!
Things should get interesting.
Thanks!
