### ISSUE TITLE
Creating accounts and admin accounts for DSJAS

### ISSUE THREAD

**Issue by jack-debug** [DSJAS/DSJAS#20]
Hello,
I installed DSJAS with Docker from the source. I have it working but I don't know how to create an account for scambaiting nor how to access the admin dashboard. How do I do this? Thanks.

**Comment by SinisterSpatula** [comment]
https://github.com/DSJAS/DSJAS/blob/master/docs/administration/Access%20management.md is the page that describes this.  The docs are in the various folders inside of /doc/ in the repo.

**Comment by ethanv2** [comment]
Please also see https://github.com/DSJAS/DSJAS/blob/master/docs/docker/Default%20credentials.md for the default logins for docker containers. You can access the admin dashboard at http://localhost/admin/user/SignIn.php . Once logged in, you can change your password and other settings in their respective sections of the admin panel.

**Comment by jack-debug** [comment]
Thanks!
