### ISSUE TITLE
Multiple Blank Pages

### ISSUE THREAD

**Issue by darkcristle** [DSJAS/DSJAS#24]
Hi, 
I am in no way a coder, just trying to set this up.

I navigated my way through installation and came across a few issues, most of which I was able to figure out for myself.  For example the directory the xampp/MAMP needs to be set to is the dsjas-master > public not dsjas-master.  

However I just came across an issue I can not seem to figure out.  I got through the installation completely, database is set up, etc.   However many pages are completely blank.

I have not made an exhaustive list but here are the few that seem to work.  If you would like me to test all pages I can do so.  Issues occur with both direct navigation (putting the file path directly into the browser) as well as navigating with links.
(*=localhost:8888/admin/)
*install - all pages load correctly
*dashboard.php - blank no error
*index.php -blank no error
*stats.php - works 
*status-update.php - blank no error
*bank/ - all pages and subdirectories blank no error
*settings/mod.php - works
*settings/ext.php - shows coming soon page
*settings/advanced.php - works
*settings/editUser - blank no errors

This is probably just user error.  Let me know if there is anything I can do.  According to map I am currently running PHP 7.4.1.  I tried downgrading to 7.3.7 and the error persisted.  I have checked that I am running the proper visual studio version.  I have checked that read/write permissions are correct.  

Edit: It is running on an ec2 AWS server.  Windows 2019, tc2.small.

Thanks

**Comment by SinisterSpatula** [comment]
When you copy the repository, make sure you are not just clicking on download zip, instead grab the zip from releases section, or if you use git commands make sure to add git recursive submodules, otherwise you might have missing stuff in the hooks folder, which will cause some pages to be blank.

**Comment by darkcristle** [comment]
That worked!

Thank you for your fast response and for making such an in depth tool.

**Comment by ethanv2** [comment]
No problem. Please see #5 for a technical explanation of this problem.

By the way, status-update.php is an API endpoint and should not be directly visited in the browser - so don't panic when it still doesn't show anything useful once the site is fixed.

For any future problems, there is likely some help in the [documentation](https://github.com/DSJAS/DSJAS/tree/master/docs). The [FAQ](https://github.com/DSJAS/DSJAS/blob/master/docs/FAQ.md) and [install guides](https://github.com/DSJAS/DSJAS/tree/master/docs/install) are a good place to start.

Good luck and happy scambaiting.
