### ISSUE TITLE
Module API: Write up and progress

### ISSUE THREAD

**Issue by ethanv2** [DSJAS/DSJAS#27]
In the process for the next release, I'm shifting focus over to the long-planned module API before I take the plunge into trying to design/implement extensions from scratch. So far, the idea for the module API is that it will consist of a set of JavaScript modules that can be accessed using a standard ES6 ```import``` statement from a path provided by a global script that DSJAS provides (similar in spirit to the ```THEME_API``` constant for themes).

The API will be split into two parts: the client side part and the remote part. The client side part will be the JS modules mentioned above and the remote will be a set of PHP API endpoints for the module APIs to use. Security-wise, I am not sure how this can work, because it would be nice for modules to be able to do some priviledged operations - like checking credentials for validity. Perhaps a similar system to the current CSRF system can be used to insert a token into the page each page load, and that token can then be used to authenticate to the module API? Suggestions appreciated.

### APIs

- [x] API for getting current theme name
- [x] API for getting current bank name
- [x] API for getting current bank domain
- [x] API for getting current username
- [x] API for getting current user's accounts
- [x] API for getting an account's balance
- [x] APIs for manipulating user sessions
- [x] API for adding event handlers to the login form submit, which will all be handled in sequence (prevent module conflicts, such as 2FA with frustrating login process)
- [x] API for pre-verifying user credentials in login forms

### General stuff

- [x] Implement API bootstrapper (provide constants, authorisation tokens, etc.)
- [x] Implement security system for remote API
- [x] Update documentation
- [x] Write new documentation for new APIs (same format as theme APIs)
- [x] Update module loader to load new API bootstrapper

**Comment by SinisterSpatula** [comment]
A request if it's possible, can we get access to the full user's info, like not just his username but everything about him like user.firstname, user.lastname, user.phonenumber, user.email?  It would be helpful for 2FA.

**Comment by ethanv2** [comment]
DSJAS doesn't store any phone number for the users yet. Would you be interested in having me change the database to store phone numbers? That shouldn't be too hard to implement, but I would have to adjust the admin panel.

**Comment by SinisterSpatula** [comment]
Yes please, sorry I thought it had that field already, but yes that one would be very valuable for 2FA.

**Comment by ethanv2** [comment]
Update on security system progress: turns out I was *really* overthinking this problem. I can just use the fact that the PHPSESSID cookie is not available to CORS requests as an authentication method. Modules can't access sensitive data about the user when the user isn't logged in anyway.

As for endpoints for verifying login attempts, I may just allow this as an open endpoint with a rate limit to prevent brute force attempts - which may be possible using the regular endpoint anyway. I will have to see what comes around.

More updates to come. See checklist above for details.

**Comment by ethanv2** [comment]
Done. Planned to merge into mainline tomorrow.
