### ISSUE TITLE
Help with installing

### ISSUE THREAD

**Issue by goshkata58** [DSJAS/DSJAS#3]
Hello, I am not very good at coding and I don't know how to work with either xampp and mamp to host the site. I also can't find any tutorials on how to install the DSJAS. Can someone help me

**Comment by goshkata58** [comment]
nvm

**Comment by ethanv2** [comment]
Hello,

Sorry I didn't reply in time, but if you still need some help, please see the install guide in the documentation, located [here](https://github.com/DSJAS/DSJAS/tree/master/docs/install).

If you need any specific help, open another issue or reply here.

Good luck with your install and happy scambaiting

**Comment by goshkata58** [comment]
> Hello,
> 
> Sorry I didn't reply in time, but if you still need some help, please see the install guide in the documentation, located [here](https://github.com/DSJAS/DSJAS/tree/master/docs/install).
> 
> If you need any specific help, open another issue or reply here.
> 
> Good luck with your install and happy scambaiting

Hi can you give me an email or discord to contact you. it is not connected with the DSJAS and it is not that urgent :)

**Comment by ethanv2** [comment]
If possible, please email DSJAS@protonmail.com for DSJAS related communications
