### ISSUE TITLE
Can't open admin panel and no money in account (no accounts)

### ISSUE THREAD

**Issue by MrSlavman** [DSJAS/DSJAS#32]
I'm not sure if I'm just not understanding the tutorial but I don't understand how to open the admin panel and my I have nothing in the 'My Accounts' tab and when I press Apply Now it just says there's a technical fault. Can I get any help or guidance?

**Comment by ethanv2** [comment]
Hi there. Please see my reply to [this issue](https://github.com/DSJAS/DSJAS/issues/33) for instructions on getting into the admin panel.

As for having no accounts, don't worry: you can create them in the admin panel under the bank account management pane. The "technical fault" that the bank pages show is just a fake message based on the fact that there isn't actually a mechanism for non-admins to create accounts on the site. Don't worry, your site is working fine.

If you need any more help, shoot me back a reply and I'll get back to you. Good luck.

**Comment by ethanv2** [comment]
I'm going to close this. Feel free to comment and re-open if you still need help. Good luck!
