### ISSUE TITLE
PHP Fatal Error

### ISSUE THREAD

**Issue by jack-debug** [DSJAS/DSJAS#34]
Hi, I am using the DSJAS docker container from the latest commit on my macOS. I ran the container and attempted to go to localhost and 127.0.0.1 but was presented with an Apache 2.4.38 500 Internal Server Error. The details said "The server encountered an internal error or misconfiguration and was unable to complete your request."

The Docker container outputted this when it happened (IP addresses redacted for obvious reasons)

`DSJAS       | [21/Nov/2021:11:26:11 +0000] "GET / HTTP/1.1" 500 799 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36"`

`DSJAS       | [Sun Nov 21 11:26:11.700662 2021] [core:alert] [pid 17] [client] /var/www/html/.htaccess: Invalid command 'Header', perhaps misspelled or defined by a module not included in the server configuration`

What should I do to troubleshoot this?

**Comment by ethanv2** [comment]
Hopefully fixed in 8b2ef49 and b87d985. Try out the latest version and see if it fixes the issue.

**Comment by jack-debug** [comment]
This commit seems to have fixed the 500 Internal Server Error but new problems have been brought up. The favicon is displayed but no webpage appears. Peering into the console output gives us this
`DSJAS       | [Sun Nov 21 12:42:53.465833 2021] [php7:warn] [pid 18] [client] PHP Warning:  require_once(vendor/hooks/src/gburtini/Hooks/Hooks.php): failed to open stream: No such file or directory in /var/www/html/include/Module.php on line 22`

`DSJAS       | [Sun Nov 21 12:42:53.466066 2021] [php7:error] [pid 18] [client] PHP Fatal error:  require_once(): Failed opening required 'vendor/hooks/src/gburtini/Hooks/Hooks.php' (include_path='.:/usr/local/lib/php') in /var/www/html/include/Module.php on line 22`

Is this an issue on my end? If so what should I do to fix it?

**Comment by ethanv2** [comment]
Simple fix for that one. You just need to [fetch submodules](https://github.com/DSJAS/DSJAS/blob/master/docs/FAQ.md#the-site-fails-to-load-it-says-something-about-require_once-failed-to-open-stream).

Just run ``git submodule update --init --recursive``

**Comment by jack-debug** [comment]
Great, seems to be working fine now. Thanks!
