### ISSUE TITLE
User Accounts page only shows 1 account (but has more in Admin) and no balance

### ISSUE THREAD

**Issue by quartapound** [DSJAS/DSJAS#38]
Excellent project.
Nearly got things fully working, but the accounts page only ever shows one account, and no balances.
Running from Docker.
started with  git clone --recursive https://github.com/DSJAS/DSJAS.git

docker-compose build
docker-compose up

I can successfully create new users , new accounts, auto generate accounts.  They are visible in the Admin dashboard, but it only ever shows a single account on the user account page, and no balance or numbers.
I've tried running git submodule update --init --recursive
![image](https://user-images.githubusercontent.com/24831662/148877592-56d5d59c-b9ae-480b-ba27-236630614481.png)
pic only has the top account, no balance

![image](https://user-images.githubusercontent.com/24831662/148878568-b1c7c3ac-a83b-4e7a-b13f-2b1a159631f4.png)
this is the admin page for the same user, there are also balances for the accounts

can someone point me in the right direction?

**Comment by ethanv2** [comment]
I've found the error - caused by experimental changes to the way balances are displayed. Specific error message:
```
[Tue Jan 11 08:13:42.569405 2022] [php7:error] [pid 17] [client 172.18.0.1:42196] PHP Fatal error:  Uncaught Error: Class 'NumberFormatter' not found in /var/www/html/include/api/theme/Dashboard.php:126\nStack
trace:\n#0 /var/www/html/admin/site/UI/default/user/Dashboard.php(136): formatCurrency('1200.00')\n#1 /var/www/html/include/Theme.php(180): getTheme()\n#2 /var/www/html/include/DSJAS.php(97): Theme->loadTheme()\n#3 /var/www/html/user/Dashboard.php(46): dsjas('/var/www/html/u...', 'user/', Object(Closure), 'all', Array)\n#4 {main}\n  thrown
in /var/www/html/include/api/theme/Dashboard.php on line 126, referer: http://localhost/user/Login.php
```

This could be because the required PHP extension is not installed in docker. I'll work on a patch for you.

**Comment by ethanv2** [comment]
Sorry for the wait. Should be fixed as of 2364d30. Run
```
git pull
docker-compose down && docker-compose build --no-cache
```
and everything should straighten out for you. Tell me if you have any other issues.

**Comment by quartapound** [comment]
Excellent support thank you for the speedy reply!
 
That worked perfectly, it's now populating - much better! :D

I do notice that there's a double $$ on the balances on  Accounts.php page and the Manage.php page, but  it looks proper (only 1 $ sign) on the Dashboard.php
![image](https://user-images.githubusercontent.com/24831662/149002260-6500dd6c-83ea-43eb-b2ac-a49fdd0b245f.png)



Also, I only seem to get white pages for the Felicity-Bank  theme,  looks like this error is associated.

`DSJAS           | [Tue Jan 11 18:36:21.485509 2022] [php7:error] [pid 28] [client 172.18.0.1:59056] PHP Fatal error:  Uncaught Error: Call to undefined function str_contains() in /var/www/html/admin/site/UI/Felicity-Bank/Bootstrap.php:35\nStack trace:\n#0 /var/www/html/include/Theme.php(172): getBootstrap()\n#1 /var/www/html/include/DSJAS.php(97): Theme->loadTheme()\n#2 /var/www/html/Index.php(62): dsjas('/var/www/html/I...', '/', Object(Closure))\n#3 {main}\n  thrown in /var/www/html/admin/site/UI/Felicity-Bank/Bootstrap.php on line 35`

Super impressive software, Thank you!

**Comment by ethanv2** [comment]
Both should be fixed now. Do another git pull. This time, don't run docker-compose with the "--no-cache" flag; it's unneeded and will slow down this build for you.

Thanks for spotting them!

**Comment by quartapound** [comment]
Really fantastic support!  All is working, now to have some fun!
Thank you again
