### ISSUE TITLE
help installing #4

### ISSUE THREAD

**Issue by jester223** [DSJAS/DSJAS#4]
hello i am trouble figuring out exactly what file i am spose to choose for the directory root for mamp and how to get the web installer going. any help would be appreciated

**Comment by ethanv2** [comment]
Hi. I noticed you closed the issue: are you still in need of help? Any problems you have getting set up, I can give you a hand with and point you in the right direction.

As for you initial question, if you downloaded DSJAS from the [releases tab](https://github.com/DSJAS/DSJAS/releases), you can just extract the zip file and set the resulting folder as the root in MAMP. You will probably want to put it somewhere safe, like a folder in your home directory (C:\Users\username\DSJAS, for example).

If you were confused about the instructions telling you to use the **public** folder, don't worry: that's only if you're downloading a development build (in which case, you will have more than just a zip file).

If you need any more help, just reopen the issue. Good luck!

**Comment by jester223** [comment]
with install i managed to get everything installed my issue now is i can't figure out how to enable url spoofing. The docs were not exactly clearly on what to do

**Comment by ethanv2** [comment]
Ah, right - no worries. If you would like, I can write up some basic guides on how to perform it. I'll add it to the todo list.

Essentially, you need to edit the *hosts* file on your computer to redirect when you go to the DSJAS location (which will be the localhost, or **127.0.0.1**).

Here's a few guides on how to edit the hosts file:

1. [For Windows](https://www.lifewire.com/how-to-edit-the-hosts-file-153661)
1. [For Linux or MacOS](https://linuxize.com/post/how-to-edit-your-hosts-file/)

You will want to add a rule which redirects the **127.0.0.1** domain to whatever domain you wish to spoof. This will fool the browser into loading DSJAS when it would normally attempt to go to the website. You can spoof whatever domain you want (literally anything, even google.com!). The changes only affect your local machine, though.

In the DSJAS settings, you will want to put in the URL which you set in the hosts file. It's fine if you don't, but DSJAS can update certain visual stuff to make it more convincing if you do use this value.

One last thing: **make sure** you edit the hosts file on whatever machine you will be accessing the site from. It only affects that single machine. So, if you're using a virtual machine (which I highly recommend), you need to do it on your main computer and in the virtual machine.

If you need any more help, just reply or type "Windows hosts file spoofing" into a search engine. Good luck and happy scambaiting.

**Comment by ethanv2** [comment]
I've added a full guide on URL spoofing to the documentation. In a future update, I'll link it in the installer and/or the settings in the admin panel.

https://github.com/DSJAS/DSJAS/blob/master/docs/administration/A%20Guide%20to%20URL%20Spoofing.md

Hopefully that should be nice and clear and you should be all set.

**Comment by jester223** [comment]
ok this just a quick question on enabling modules cause in the admin panel i know you change the 0 to a 1 to enable but what i can't figure out is why its not saving the change when i save it. also do i have to change it in the both the module and extension file?

**Comment by ethanv2** [comment]
Sorry, I may have misunderstood, but are you trying to enable/disable modules manually in the advanced settings panel? If so, don't do that and just use the built-in panel in the modules/themes settings panel (click on the modules tab). Editing the config files manually is only really for fixing serious problems or recovering from errors.

**Comment by jester223** [comment]
> may you don't understand what my issue is when i go and toggle them on in module/themes settings and save when i go back to it still doesn't show it toggled on
> 
> Sorry, I may have misunderstood, but are you trying to enable/disable modules manually in the advanced settings panel? If so, don't do that and just use the built-in panel in the modules/themes settings panel (click on the modules tab). Editing the config files manually is only really for fixing serious problems or recovering from errors.

**Comment by ethanv2** [comment]
That's strange, and sounds like a bug to me. Let's open a new issue so that we can separate it out from this one.
