### ISSUE TITLE
DSJAS doesn't load when visiting localhost after following install directions. Can you please make an install video?

### ISSUE THREAD

**Issue by calvincorrieri** [DSJAS/DSJAS#41]
I saw that on your YouTube channel you had a few videos discussing the features but none showing how to properly install and configure DSJAS. I'm trying to install it on a linux VM and nothing I try works. I've followed the instructions step by step, starting from the beginning each time. I've done a full clean linux install. I know everything is up to date. Might be missing some dependencies but none that are specified in the instructions. A video walkthrough would be an absolute godsend. I don't know what I'm doing wrong and the current documentation is of no help.

**Comment by ethanv2** [comment]
Do you have a server up and running? It sounds like your server isn't actually running. Try following the instructions in the order laid out [here](https://github.com/DSJAS/DSJAS/tree/master/docs/install#dsjas-documentation---installation-section). It shows you how to install MAMP (I recommend this one if you're a beginner with web servers) and start it out of the right directory.

Be sure to download from the releases page, not from the source code. Unless you want to write code for the project, there's no need to download the source.

**Comment by calvincorrieri** [comment]
I figured out a workaround. Instead of trying to run it in a VM, I got it running it locally using MAMP. Just had to bash my head against the wall for a little longer.
