### ISSUE TITLE
Missing pages?

### ISSUE THREAD

**Issue by JEREDEK** [DSJAS/DSJAS#44]
I managed to install the page manually, but now it's missing pages for /support, /user/apply, /CPRewards and /services
Is there somewhere I can download these pages from?
Example image:
![image](https://user-images.githubusercontent.com/24723767/154667505-75a1db65-7712-4d64-abed-f826d9b23a79.png)

**Comment by ethanv2** [comment]
Are there any pages which are working correctly? Try navigating to <domain>/admin/user/SignIn.php and logging in with the admin credentials you set up in the installer. After that, what version does it show at <domain>/admin/settings/update.php? In the lastest version, most of those links have been phased out.

**Comment by JEREDEK** [comment]
Yeah, most of them are working. All the main features are OK, just those pages that i listed.
Here's my update page
![image](https://user-images.githubusercontent.com/24723767/154749169-7bb454d3-4602-4e01-a32e-d39176723386.png)

**Comment by ethanv2** [comment]
That sounds like a problem with the configuration of your webserver, especially given that the 404 override isn't working. Is your HTTP root configured to "AllowOverride all" in your Apache config? Without that, Apache will refuse to load the .htaccess configuration.

**Comment by JEREDEK** [comment]
Yep, it's set to all

**Comment by calvincorrieri** [comment]
Try setting it up using MAMP and see if that works. That way you know the server is properly configured out of the box, all you gotta do is point it to the DSJAS folder. Then go through the setup like normal. Also set the MAMP port to 80 if you want to DNS spoof on a VM.

**Comment by ethanv2** [comment]
Any further progress on this problem?

**Comment by JEREDEK** [comment]
Unfortunately, I've been kinda busy lately, but i've spent some time looking into it, and I have no idea why it might be breaking
