### ISSUE TITLE
White page on admin login

### ISSUE THREAD

**Issue by JEREDEK** [DSJAS/DSJAS#45]
I go through the whole setup, but when I try to log into the admin panel, all it shows is just a blank page.
The main page works fine, but not the admin login

**Comment by JEREDEK** [comment]
Also, now that i look at it, the whole styling seems to be completely gone?
![image](https://user-images.githubusercontent.com/24723767/162238546-bb8ee244-a54b-4333-91ff-1d6f31f914de.png)

**Comment by ethanv2** [comment]
Try pressing Ctrl-F5 and see if your browser re-downloads the styling. Failing that, open the developer console (Ctrl-Shift-I). Click on console and see if you can spot any download errors for scripts.

**Comment by JEREDEK** [comment]
Just these two
![image](https://user-images.githubusercontent.com/24723767/162275271-591f3467-2b5a-49ec-89a4-4ee08f7e6116.png)

**Comment by ethanv2** [comment]
Does the sources tab show any CSS files being downloaded? They will be located in a subfolder (likely beginning with either "assets" or "admin")

This looks like it may be your webserver failing to process the .htaccess rules - similar to the probable cause of your other issue also. Make sure that AllowOverride is set to all for the DSJAS folder in your Apache configuration

**Comment by JEREDEK** [comment]
OK, i had enough time to get back into it, and after indeed setting AllowOverride to all, I was met with this error:
/var/www/html/cheapfinantial.xyz/public_html/.htaccess: Invalid command 'RewriteEngine', perhaps misspelled or defined by a module not included in the server configuration

**Comment by ethanv2** [comment]
You need to pull submodules. Go to your server directory and try following these instructions: https://github.com/DSJAS/DSJAS/blob/master/docs/FAQ.md#the-site-fails-to-load-it-says-something-about-require_once-failed-to-open-stream

**Comment by JEREDEK** [comment]
OK, pulled submodules and we are once again back at the poorly formatted website. It looks identical to the first SS i shared, but i can also supply this error:
PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/web/public_html/admin/site/UI//components/Footer.php' (include_path='.:/usr/share/php') in /var/www/html/web/public_html/admin/site/UI/default/Index.php:199\nStack trace:\n#0 /var/www/html/web/public_html/include/Theme.php(180): getTheme()\n#1 /var/www/html/web/public_html/include/DSJAS.php(97): Theme->loadTheme()\n#2 /var/www/html/web/public_html/Index.php(62): dsjas()\n#3 {main}\n  thrown in /var/www/html/web/public_html/admin/site/UI/default/Index.php on line 199, referer: http://www.web.xyz/admin/install/Success.php

**Comment by ethanv2** [comment]
Have you also init'd configs. When pulled from git, you need to run the script in ``scripts/Install.py`` before running. It looks like you have no theme initialised, so DSJAS is failing to load properly.

**Comment by JEREDEK** [comment]
OK, that fixed it!
That's weird tho, i didn't have to do that any of the previous times i installed DSJAS.
Thanks so much for the help!

**Comment by ethanv2** [comment]
No worries at all. Any more issues and the documentation (docs folder in the source) should be of some help - either that or open a new issue.
