### ISSUE TITLE
index page fails to load with 500 code

### ISSUE THREAD

**Issue by steveunixson** [DSJAS/DSJAS#57]
i'm trying to run it in docker but i get this error

Failed opening required 'vendor/hooks/src/gburtini/Hooks/Hooks.php' (include_path='.:/usr/local/lib/php') in /var/www/html/include/Module.php on line 22

**Comment by ethanv2** [comment]
Please try running ``git submodule update --init`` from your host and then re-building the server container.

**Comment by steveunixson** [comment]
thanks! it worked!

**Comment by ethanv2** [comment]
No problem at all.
