### ISSUE TITLE
module not enabling

### ISSUE THREAD

**Issue by jester223** [DSJAS/DSJAS#6]
ok i opened a new issue as i said before when able them in the settings and save then go back it shows them not enabled. I even tried enable them in the module file and it still does the same thing.

**Comment by ethanv2** [comment]
Right, so before I assign this to the bug list, can we please just double check that you're doing the following:

1. Going to the modules settings panel
2. Toggling on the module which you wish to have enabled
3. Clicking "Save changes"
4. Getting redirected back to the homepage, with a message banner appearing which states that the changes were saved successfully

If you're doing all of that and DSJAS is still not saving your module settings, it must be a bug and we can go from there.

**Comment by jester223** [comment]
i did every you said above and i have double checked this plus enabled it and left my browser then logged back in the back and still nothing, i was testing while trying to do the frustrating login module

**Comment by ethanv2** [comment]
Ah, right. Yes, DSJAS ignores hidden files in the module/theme directories, because themes and modules like to store their settings and data there.

Out of interest, are you installing the bank inside the virtual machine? If so, that's completely fine (just be sure to hide it well), but it is completely possible to install it outside the virtual machine and still manage to connect to it.

**Comment by jester223** [comment]
yeah i have it installed in my vm. i take it that if you can connect to it outside the vm would that be same case with mamp to?

**Comment by ethanv2** [comment]
I should have been more clear: if it is installed **inside** the VM, the host computer cannot see it. But, if installed on the host computer, the VM can access it using the local IP of your machine.

So, if you're paranoid about people finding it on the VM, you can just move it to outside. And, in the hosts file we talked about overriding, make sure you use the IP address of your host computer and not localhost.

**Comment by jester223** [comment]
so do i put my ip in the host file  in both my host and the vm?

**Comment by ethanv2** [comment]
Inside the VM, you will need to put it in the hosts file, but you need to provide the IP of your main computer. You'll need to get this using the command prompt: [see here](https://www.digitalcitizen.life/find-ip-address-windows/). On your main computer, you *can* put it in the hosts file for convenience (you may still want to navigate to the bank using your preferred domain), but it's really not required if you want to save yourself some work. On your main machine, you **will** want to just use localhost, as the server is on this machine.

Hopefully that makes some sense. Basically, in the VM, you need to use the IP of your main computer. On your main computer, you can just use *localhost*.

**Comment by jester223** [comment]
ok i did that but it takes me to my gateway login instead

**Comment by ethanv2** [comment]
Make sure that you use the IP in the ``ipconfig`` output which is next to the label *IPv4 Address*. I will look like this:

![](https://i.imgur.com/ffXCdUx.png)

Did you put in the address of your router by accident?

**Comment by jester223** [comment]
i got it work now thanks
