### ISSUE TITLE
Possible rewrite in Go

### ISSUE THREAD

**Issue by ethanv2** [DSJAS/DSJAS#62]
Over the last few weeks, I have looked back through the DSJAS codebase and have noticed how difficult to maintain and irritating to manage it is going to be in the future. This is partly due to the choice of language and partly due to some sloppy code quality on my part (the installer and the theming engine being particular offenders). More recent features on the site (such as statistics) are much better designed, but still have all the drawbacks of PHP and more. So, over the coming months, I hope to make it a side project of mine to rewrite this project in Go.

When I originally wrote DSJAS, I had not finished learning Go yet, and had certainly not yet finished learning everything about web development. As a result, I did not pick the best tool for the job. PHP is a templating tool - it is not suited for large, custom web applications. A large part of the DSJAS codebase is dedicated to just getting around the designed purpose of PHP (see the .htaccess file for details on what I mean). If I had used a custom HTTP router in Go, all of this complexity and the systems behind it would have been avoided. The way that themes work is another good example; DSJAS simply called ``require()`` on their theme file. A Go HTML template could replace basically the entirety of the theme engine and remove the entire requirement to learn a scripting language to just design a frontend (the drawback obviously being a loss of freedom, as arbitrary code can no longer be executed).

So, given all of this and the suitably fitting ways that Go could handle the project, I would appreciate some feedback on the idea of a full rewrite. The final product would not be anywhere near ready for use for several months at the very least, but I think that the benefits would be massive for me and those who use this tool.

What do you think?

**Comment by ethanv2** [comment]
For just a brief list of bad coding decisions that I made, here are a few:

1. Wrote a custom DB engine which ignores errors by default and makes it a pain to check them properly
2. Used INI as a format for the config files, just because there is a built-in parser in PHP
3. Used GET headers and global variables to pass around state in the request
4. Wrote a custom GET header parser to get around them being stripped by Apache when performing a mode_rewrite redirect for permalinks
5. Wrote a custom permalinks system from scratch which fails to detect some invalid URLs to this day
6. Stored a bunch of temporary data on disk due to PHP separating request state strictly into separate scripts (often useful, but some data just needs to be shared between requests)
7. Added a sort of pseudo-runtime to all scripts and modules so that they can interact with the weird and wonderful ways I wrote the DSJAS API
8. Required the use of PHP scripting for themes so that I didn't have to use proper template strings
9. Required the use of Apache due to using mod_rewrite strictly for all redirects
10. Used an .htaccess file which needs to be re-read by Apache by nature for every request, handicapping server performance

This is just a short list off the top of my head. I am hopeful that, with these lessons learnt in mind, I can go forward with better design goals than before.

**Comment by SinisterSpatula** [comment]
I haven't learned Go yet and I don't know how popular Go is.  But have you thought about perhaps doing it with nodejs/express?  It's very flexible and there is a huge library of modules that can be added to the project depending on what's needed, like date/time formating via 'moment'.  Or adding passport for authentication, etc.  I have a decent bit of experience with node.

**Comment by ethanv2** [comment]
I am not a fan of JavaScript or node and would like to avoid it where possible. I am aware of quite a few packages for Go which can fill similar roles as moment.js and passport (in fact, the standard library contains a very similar feature to Node - see https://pkg.go.dev/time).

**Comment by SinisterSpatula** [comment]
Sorry to hear that.  Good luck.

**Comment by ethanv2** [comment]
Right, I created a pinned discussion for anybody to contribute to: https://github.com/DSJAS/DSJAS/discussions/63. As said in that thread, I will make periodic updates to there.
