### ISSUE TITLE
URL Spoofing Not Working

### ISSUE THREAD

**Issue by mustachio128** [DSJAS/DSJAS#64]
I just successfully setup DSJAS. I am hosing it on a operate computer (iMac running MacOS 10.13 using MAMP) than my vm host computer so I can't simply use the localhost IP address in the hosts file nut rather the local ip of of the web server. I am able to access the bank from my VM (Running Windows 7 Ultimate in VirtualBox) by going to the local server IP but when I try to go to the spoofed url from my browser, it just says it can't be reached. I am able to ping the spoofed domain with cmd and get responses form the local ip address. Im Wondering if I'm doing something wrong of if it's a thing of modern browsers.

**Comment by jester223** [comment]
here is what i suggest or rather what i did
1. make sure mamp is running or whatever program your using to host the bank(this has to be running for your bank to work in your browser)
2.  put local ip in the host computer and your ipv4 in your vm
3. make sure to wipe the dns file on both the host computer and vm , this needs to be done after you make any changes to the host file(this is what your computer uses to associate ips with urls)  you can do this by going to command promp and typing ipconfig /flushdns

i hope this helps

**Comment by mustachio128** [comment]
Update: I've tried a few other things including: trying Firefox instead of chrome, flushing the dns, remaking the host file, changing browser settings, & restarting the VM. All to no avail. I'm not sure if this is something from using MAMP or something else but I'm only getting more confused at this point.

**Comment by ethanv2** [comment]
Sorry for the delayed response.

Just to be clear, the hosts file on the VM is the one you have modified. Is that correct?

If the browser says it cannot be reached, that usually means that it correctly looked up the IP address, but the connection failed for some other reason. Have you got the right port number? Even with the spoofed domain, if the server is not hosted on port 80, you still need to put it after the domain. (If I am misunderstanding the error message, please post a screenshot for me).

**Comment by mustachio128** [comment]
Yes, to clarify I modified the hosts file in the vm as my host is a Mac. The port in MAMP is indeed set to 80 and if I type in the up with no port, it works.

**Comment by ejv2** [comment]
Hi. I know this issue has been left for a long time, but did you ever reach a conclusion?

A common issue is that browsers were trying to connect via HTTPS when only HTTP was available. If you are still able, try explicitly typing http:// before the spoofed domain.

**Comment by ejv2** [comment]
Hello @mustachio128. Sorry for the long lag time in responses. I am going to close this issue now to help clear my backlog. Please consult your operating system documentation (or ask on their support forum) if you need any more help. If there is anything else I can help you with, please open a new issue.

Thanks and happy scambaiting.
