### ISSUE TITLE
Docker Images run but web page is blank and the following errors occur in console stndout 

### ISSUE THREAD

**Issue by linuxbass** [DSJAS/DSJAS#67]
Docker Images run but web page is blank and the following errors seen in console stndout:
 
DSJAS       | [Thu Dec 29 06:29:26.137770 2022] [php7:warn] [pid 17] [client 192.168.X.X:52674] PHP Warning:  require_once(vendor/hooks/src/gburtini/Hooks/Hooks.php): failed to open stream: No such file or directory in /var/www/html/include/Module.php on line 22
DSJAS       | [Thu Dec 29 06:29:26.138300 2022] [php7:error] [pid 17] [client 192.168.X.X:52674] PHP Fatal error:  require_once(): Failed opening required 'vendor/hooks/src/gburtini/Hooks/Hooks.php' (include_path='.:/usr/local/lib/php') in /var/www/html/include/Module.php on line 22

Fresh install of Ubuntu 22.04.1 LTS  with generic snap install of Docker: 20.10.17
(same issue occurred on older Centos 8 box as well  )

**Comment by linuxbass** [comment]
Looks like this is missing https://github.com/gburtini/PHP-Hooks-System

**Comment by ethanv2** [comment]
Please run ``git submodule update --init`` and re-build the docker container

**Comment by linuxbass** [comment]
Thank you ethanv2, yes that solved the problem. Rebuilt the container and ran after running the above git command.  Website renders fine and can login as "edna". 

I'll open a separate bug for a problem  with "admin" credentials not working.

**Comment by ethanv2** [comment]
No problem at all. Happy scambaiting.
