### ISSUE TITLE
Two-factor still generates number for non-existent accounts

### ISSUE THREAD

**Issue by BRUJOjr** [DSJAS/DSJAS#69]
If I was to try to log-in to a non-existent account called 'a' the two-factor would still pop-up and show a phone number for the account. Scammers could easily figure out this isn't a real page with that method.

**Comment by ejv2** [comment]
Hello. I will endeavor to fix this in the near future. I will simply add an API which checks if a given username exists or not. This could technically be a security vulnerability as it makes it easier to guess usernames, but I will try and create some kind of rate limit etc. to mitigate risks.

I will let you know when I have pushed a fix to master so you can test it out.

**Comment by ejv2** [comment]
Hi @BRUJOjr. Just to let you know, I will begin working on this in the next few days and will copy you in when a patch is submitted.

**Comment by ejv2** [comment]
I totally forgot that I already implemented this as of commit 1d265d8. Are you sure you are running the latest build from master?
