### ISSUE TITLE
Running DSJAS from docker container results in a blank localhost screen.

### ISSUE THREAD

**Issue by Mikeymoo5** [DSJAS/DSJAS#70]
When I try and run DSJAS through docker-compose, it starts up and then whenever I go to localhost, it is  just a blank screen. 

In the terminal, I get two repeating errors: 

DSJAS           | 172.20.0.1 - - [27/May/2023:22:13:11 +0000] "GET / HTTP/1.1" 500 1481 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
DSJAS           | [Sat May 27 22:13:49.736640 2023] [php7:warn] [pid 19] [client 172.20.0.1:53088] PHP Warning:  require_once(vendor/hooks/src/gburtini/Hooks/Hooks.php): failed to open stream: No such file or directory in /var/www/html/include/Module.php on line 22

I am on a Windows 11 PC.

**Comment by ejv2** [comment]
See #67 and follow instructions. Let me know if you have any trouble.

**Comment by Mikeymoo5** [comment]
Oops, my appologies. This was on my end.
Sorry for wasting any time, 
Thanks!

**Comment by ejv2** [comment]
No worries. Happy scambaiting.
