### ISSUE TITLE
Admin Login Not Working

### ISSUE THREAD

**Issue by Johnnyreyman** [DSJAS/DSJAS#71]
I have tried logging in with the username and password that are in the documentation and I cannot login to the dashboard with it on the docker install.

**Comment by ejv2** [comment]
What output are you getting when attempting to log in?

**Comment by ejv2** [comment]
Hi. I'm not sure if you got any further with this issue, but please make sure that you're using the admin credentials and not the default bank user credentials. The default administrator has username "admin" and password "DSJAS1234". Make sure you type this exactly and that you're using the username, not account name!

**Comment by Johnnyreyman** [comment]
I get this output when i am running the docker:
```
DSJAS-database  | 2023-09-03T22:05:44.753905Z 26 [Warning] [MY-013360] [Server] Plugin mysql_native_password reported: ''mysql_native_password' is deprecated and will be removed in a future release. Please use caching_sha2_password instead'
DSJAS-database  | 2023-09-03T22:05:44.756052Z 27 [Warning] [MY-013360] [Server] Plugin mysql_native_password reported: ''mysql_native_password' is deprecated and will be removed in a future release. Please use caching_sha2_password instead'
DSJAS           | 172.18.0.1 - - [03/Sep/2023:22:05:44 +0000] "POST /user/Login.php HTTP/1.1" 302 1927 "http://localhost/user/Login.php" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0"
DSJAS-database  | 2023-09-03T22:05:44.769469Z 28 [Warning] [MY-013360] [Server] Plugin mysql_native_password reported: ''mysql_native_password' is deprecated and will be removed in a future release. Please use caching_sha2_password instead'
DSJAS-database  | 2023-09-03T22:05:44.770492Z 29 [Warning] [MY-013360] [Server] Plugin mysql_native_password reported: ''mysql_native_password' is deprecated and will be removed in a future release. Please use caching_sha2_password instead'
DSJAS           | 172.18.0.1 - - [03/Sep/2023:22:05:44 +0000] "GET /user/Login.php?error=-1 HTTP/1.1" 200 1705 "http://localhost/user/Login.php" "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/116.0"
```

**Comment by ejv2** [comment]
And what is the error message on the login page when you try it?

**Comment by Johnnyreyman** [comment]
It says: Invalid username The entered username was not found.
Username: admin
Pass: DSJAS1234

**Comment by ejv2** [comment]
You are trying to log into the bank using the admin dashboard credentials. The admin login is at [SITE URL]/admin/user/SignIn.php.

Please try using this form and let me know if it lets you in.

**Comment by ejv2** [comment]
Hello! Did you manage to solve this issue? If so, just let me know so I can close this issue from the tracker.
