### ISSUE TITLE
activating modules for installation

### ISSUE THREAD

**Issue by jester223** [DSJAS/DSJAS#79]
so when i tried to reinstall with the new it asked for all these modules to be activated . I don't understand enough about coding that i would be afraid i would screw something up. i looked in the module and i am not seeing alot of  the modules that are listed. attachd is the message its giving me.  how do you enable these modules?
![Capture](https://github.com/DSJAS/DSJAS/assets/32504269/e6679d60-5928-4bda-9a4b-1b8964ccf55a)

**Comment by ejv2** [comment]
Hello. This is a new requirement on our end for PHP. You will need to enable these in your PHP.ini configuration file. There are instructions on how to do this [elsewhere](https://stackoverflow.com/questions/33869521/how-can-i-enable-php-extension-intl), but If you need any help, just let me know.

**Comment by jester223** [comment]
my first question is does it have to be enabled in dsjas files or in mamp? i understand i think i have to put in commands or something in command prompt. i don't remember installing it being this complicated before.

**Comment by ejv2** [comment]
Yes. Sorry for the added complication. This new requirement is to avoid strange errors later on, though, so hopefully it is worth it.

First, you need to [find your PHP.ini file](https://documentation.mamp.info/en/MAMP-Mac/FAQ/Where-can-I-find-the-php.ini-file/). In your MAMP settings, there should be a selection as to which PHP version you are using. You need to open the PHP.ini file which is in the directory corresponding to the version you have enabled.

Once you open this file (again it is called php.ini) follow the instructions in the article that I linked above to enable all the modules which are mentioned in the error message. If a module has no semi-colon at the start of its config line, it is already enabled and you don't need to do anything.

**Comment by jester223** [comment]
ok i was able tin enable all but two zip and sodium which i didn't didn't see listed . i guess i need to install these?

**Comment by ejv2** [comment]
These were built in when I wrote the documentation but aren't anymore. You'll need to download them from here:

- [sodium](https://pecl.php.net/package/libsodium)
- [zip](https://pecl.php.net/package/zip)

If you are on Windows, download the latest which has the DLL link next to it. For all of them, you will want the thread safe version. Download the DLLs and then put them in the ext folder in the folder for whichever version of PHP you are using. Make sure you don't rename the files! Then, just add the following to your php.ini file below the other extensions:

```ini
extension=php_zip.dll
extension=php_sodium.dll
```

Then you need to restart the webserver.

**Comment by jester223** [comment]
ok i have them all enabled i restarted it but i am still getting the error

**Comment by ejv2** [comment]
Did you manage to fix it?
