### ISSUE TITLE
issues with installation module

### ISSUE THREAD

**Issue by jester223** [DSJAS/DSJAS#80]
my new issue now is i have all extensions enabled yet i am still getting the error that they are not enabled

**Comment by ejv2** [comment]
I've just added some debugging tools to the repository to help with sorting this out. To help you further, I will need some information.

1. Please download [this script](https://raw.githubusercontent.com/DSJAS/DSJAS/master/scripts/checkmods.php) and put it in your public folder. Then, go to [BANK URL]/checkmods.php and screenshot the output for me
2. Please give me your PHP version
3. Please attach a copy of your PHP.ini file

**Comment by jester223** [comment]
i'm using php 7.1
![mod check](https://github.com/DSJAS/DSJAS/assets/32504269/46bf44ee-1ab6-4448-b49e-9341dc7e4ef6)
7

it wouldn't let me attach my php file  but you can download it here: https://www.mediafire.com/file_premium/qyoykw2rq8etngv/php.ini/file

**Comment by ejv2** [comment]
You haven't enabled any of the PHP extensions in your config file. You'll need to remove the semi-colon at the start of the line for each extension that the error mentions. It seems that sodium and zip *are* built in to your version of PHP. I've attached a picture of what it should look like once finished. The line numbers in the screenshot are the ones you will want to change.

![screenshot-231001-0154-39](https://github.com/DSJAS/DSJAS/assets/45273541/87b66b16-0749-421c-9140-32ce5e93e3a7)

**Comment by jester223** [comment]
ok after making the changes its still giving me the error. I ran the check mod script and its say now its missing sodium. omg this so frustrating but worth it if i can get this dang thing to work.

**Comment by ejv2** [comment]
It is likely that it isn't installed then. The easiest thing to do is probably to re-install XAMPP (or update to the latest version if that option exists).

On later versions, when you edit the extensions part of the php.ini, it won't read exactly the same and the ".dll" part at the end will probably be missing. Just ignore this and remove the semi-colon like before.

**Comment by Owen000** [comment]
I'm also encountering the same issue, on both xampp and mamp on multiple different version I encounter "The module sodium is missing Please install or enable this module." on checkmods.php

**Comment by ejv2** [comment]
@Owen000 Does that mean that you solved the issue then?

**Comment by ejv2** [comment]
As we've got some advice for solving this from users in the thread, I'm going to mark this as completed. @jester223, please feel free to re-open if you run in to any more issues.

**Comment by ejv2** [comment]
For anybody experiencing this issue with the sodium module, please use the later v0.1.5-alpha version, which does not require sodium for installation.
