### ISSUE TITLE
Cannot Get Setup To Work.

### ISSUE THREAD

**Issue by Gavin7199119** [DSJAS/DSJAS#83]
Hello I'm having a problem getting the setup to work, I have done all the steps correctly but after doing so I'm getting this PHP error saying that the requirements are not met after going to "localhost"

**Comment by ejv2** [comment]
Hello. Please download [this script](https://raw.githubusercontent.com/DSJAS/DSJAS/master/scripts/checkmods.php) to your public folder, navigate to <http://localhost/checkmods.php> and screenshot the output for me.

**Comment by ejv2** [comment]
Hi @Gavin7199119. I'm going to close this issue now just to clear my todo list, but if you still need help please feel free to re-open. Thanks!
