### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by Balii1** [DSJAS/DSJAS#84]
immediately throws me the last stage of setup instead of the first step and i cant go back to the first stage

**Comment by ejv2** [comment]
Do you have a valid configuration file? If not, please run the install scripts as described [here](https://github.com/DSJAS/DSJAS/discussions/74#discussioncomment-6890090). If so, please attach the contents.

**Comment by ejv2** [comment]
Hi @Balii1. Did you ever make any progress with this? I'm going to close the issue just to clear my todo list, but if you are still having trouble please feel free to re-open. Thanks!
