### ISSUE TITLE
removing dot .php from url

### ISSUE THREAD

**Issue by jester223** [DSJAS/DSJAS#9]
is there way to remove the .php from the url so that way the fake bank url seem more legitmate?

**Comment by ethanv2** [comment]
Hi. Currently, DSJAS does not have a feature to remove the PHP extension from URLs, and I do not have any plans to add such a feature for technical reasons (please see [permalinking documentation](https://github.com/DSJAS/DSJAS/blob/master/docs/core/Lifecycle%20of%20a%20request.md#the-index-file)).

At some point in the later future, I may redesign the permalinks system to make it possible to hide the extension from the URL, but that would require quite a fundamental redesign of the theme system.
